In [1]:
from keras.models import Sequential, Model
from keras import layers
from keras import Input

seq_model = Sequential()                                               
seq_model.add(layers.Dense(32, activation='relu', input_shape=(64,)))
seq_model.add(layers.Dense(32, activation='relu'))
seq_model.add(layers.Dense(10, activation='softmax'))

input_tensor = Input(shape=(64,))                                      
x = layers.Dense(32, activation='relu')(input_tensor)                  
x = layers.Dense(32, activation='relu')(x)                             
output_tensor = layers.Dense(10, activation='softmax')(x)              

model = Model(input_tensor, output_tensor)                             

model.summary() 

/home/farid/.local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 64)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_5 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_6 (Dense)              (None, 10)                330       
Total params: 3,466
Trainable params: 3,466
Non-trainable params: 0
_________________________________________________________________


In [2]:
print("Params: " ,64*32 +32)

Params:  2080


In [3]:
print("Params: " ,32*32 +32)

Params:  1056


In [4]:
print("Params: " ,32*10 +10)

Params:  330


In [6]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')      
import numpy as np                                                       
x_train = np.random.random((100, 64))
y_train = np.random.random((100, 10))

model.fit(x_train, y_train, epochs=10, batch_size=128)                   

score = model.evaluate(x_train, y_train)                                 

Epoch 1/10
100/100 [==============================] - 0s 1ms/step - loss: 11.6957
Epoch 2/10
100/100 [==============================] - 0s 22us/step - loss: 11.6759
Epoch 3/10
100/100 [==============================] - 0s 26us/step - loss: 11.6675
Epoch 4/10
100/100 [==============================] - 0s 56us/step - loss: 11.6609
Epoch 5/10
100/100 [==============================] - 0s 23us/step - loss: 11.6545
Epoch 6/10
100/100 [==============================] - 0s 34us/step - loss: 11.6495
Epoch 7/10
100/100 [==============================] - 0s 22us/step - loss: 11.6453
Epoch 8/10
100/100 [==============================] - 0s 39us/step - loss: 11.6410
Epoch 9/10
100/100 [==============================] - 0s 29us/step - loss: 11.6372
Epoch 10/10
100/100 [==============================] - 0s 362us/step


### Question-answering model 

In [12]:
from keras.models import Model
from keras import layers
from keras import Input

text_vocabulary_size = 10000
question_vocabulary_size = 10000
answer_vocabulary_size = 500

text_input = Input(shape=(None,), dtype='int32', name='text')            

embedded_text = layers.Embedding(
    text_vocabulary_size,64)(text_input)                                

encoded_text = layers.LSTM(32)(embedded_text)                            

question_input = Input(shape=(None,),
                       dtype='int32',
                       name='question')                                  

embedded_question = layers.Embedding(
    question_vocabulary_size,32)(question_input)
encoded_question = layers.LSTM(16)(embedded_question)

concatenated = layers.concatenate([encoded_text, encoded_question],
                                  axis=-1)                               

answer = layers.Dense(answer_vocabulary_size,
                      activation='softmax')(concatenated)                

model = Model([text_input, question_input], answer)                      
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['acc'])

In [38]:
x = np.zeros((3,4))
print(np.random.randint(0, x.shape[1]-1, size=x.shape[0]))
x[np.arange(x.shape[0]),np.random.randint(0, x.shape[1]-1, size=x.shape[0])] = 1
print(x)

[1 0 0]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [41]:
import numpy as np

num_samples = 1000
max_length = 100

text = np.random.randint(1, text_vocabulary_size,
                         size=(num_samples, max_length))                   
question = np.random.randint(1, question_vocabulary_size,
                             size=(num_samples, max_length))

answers = np.zeros((num_samples,answer_vocabulary_size))
answers[np.arange(answers.shape[0]),np.random.randint(0, answers.shape[1], size=answers.shape[0])] = 1

model.fit([text, question], answers, epochs=10, batch_size=128)            

model.fit({'text': text, 'question': question}, answers,                   
          epochs=100, batch_size=128)

Epoch 1/10
1000/1000 [==============================] - 1s 1ms/step - loss: 6.3545 - acc: 1.0000e-03
Epoch 2/10
1000/1000 [==============================] - 1s 1ms/step - loss: 6.1810 - acc: 0.0020
Epoch 3/10
1000/1000 [==============================] - 1s 1ms/step - loss: 6.1200 - acc: 0.0050
Epoch 4/10
1000/1000 [==============================] - 1s 1ms/step - loss: 6.0173 - acc: 0.0060
Epoch 5/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.9046 - acc: 0.0100
Epoch 6/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.7733 - acc: 0.0150
Epoch 7/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.6802 - acc: 0.0200
Epoch 8/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.5430 - acc: 0.0260
Epoch 9/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.4542 - acc: 0.0210
Epoch 10/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.3843 - acc: 0.0300
Epoch 1/100
1000/1000 [==

1000/1000 [==============================] - 1s 1ms/step - loss: 2.1141 - acc: 0.6950
Epoch 74/100
1000/1000 [==============================] - 1s 1ms/step - loss: 2.0477 - acc: 0.7100
Epoch 75/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.9955 - acc: 0.7270
Epoch 76/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.9594 - acc: 0.7360
Epoch 77/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.9354 - acc: 0.7520
Epoch 78/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.8674 - acc: 0.7560
Epoch 79/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.8281 - acc: 0.7800
Epoch 80/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.7883 - acc: 0.7730
Epoch 81/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.7490 - acc: 0.7970
Epoch 82/100
1000/1000 [==============================] - 1s 1ms/step - loss: 1.7000 - acc: 0.8190
Epoch 83/100
1000/1000 

### Three-output model

In [44]:
from keras import layers
from keras import Input
from keras.models import Model
vocabulary_size = 50000
num_income_groups = 10

posts_input = Input(shape=(None,), dtype='int32', name='posts')
embedded_posts = layers.Embedding(vocabulary_size, 256)(posts_input)
x = layers.Conv1D(128, 5, activation='relu')(embedded_posts)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(256, 5, activation='relu')(x)
x = layers.Conv1D(256, 5, activation='relu')(x)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(256, 5, activation='relu')(x)
x = layers.Conv1D(256, 5, activation='relu')(x)
x = layers.GlobalMaxPooling1D()(x)
x = layers.Dense(128, activation='relu')(x)

age_prediction = layers.Dense(1, name='age')(x)               
income_prediction = layers.Dense(num_income_groups,
                                 activation='softmax',
                                 name='income')(x)
gender_prediction = layers.Dense(1, activation='sigmoid', name='gender')(x)

model = Model(posts_input,
              [age_prediction, income_prediction, gender_prediction])

Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead


In [45]:
model.compile(optimizer='rmsprop',
              loss=['mse', 'categorical_crossentropy', 'binary_crossentropy'])

model.compile(optimizer='rmsprop',                             
              loss={'age': 'mse',                              
                    'income': 'categorical_crossentropy',      
                    'gender': 'binary_crossentropy'})

In [46]:
model.compile(optimizer='rmsprop',
              loss=['mse', 'categorical_crossentropy', 'binary_crossentropy'],
              loss_weights=[0.25, 1., 10.])

model.compile(optimizer='rmsprop',                            
              loss={'age': 'mse',                             
                    'income': 'categorical_crossentropy',     
                    'gender': 'binary_crossentropy'},         
              loss_weights={'age': 0.25,                      
                            'income': 1.,                     
                            'gender': 10.})   

In [49]:
num_samples = 1000
max_length = 500
posts = np.random.randint(1, vocabulary_size,
                         size=(num_samples, max_length))                   

age_targets = np.random.randint(1, 99,size=(num_samples))                   


income_targets = np.random.randint(1, 100000,size=(num_samples,num_income_groups))
income_targets[np.arange(income_targets.shape[0]),np.random.randint(0, income_targets.shape[1], size=income_targets.shape[0])] = 1


gender_targets =np.random.random_integers(0, 1,size=(num_samples))

model.fit(posts, [age_targets, income_targets, gender_targets],        
          epochs=10, batch_size=64)

model.fit(posts, {'age': age_targets,                                  
                  'income': income_targets,                            
                  'gender': gender_targets},                           
          epochs=10, batch_size=64) 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  del sys.path[0]


Epoch 1/10
1000/1000 [==============================] - 15s 15ms/step - loss: 5963463.3640 - age_loss: 2122.3955 - income_loss: 5962900.2560 - gender_loss: 3.2475
Epoch 2/10
1000/1000 [==============================] - 16s 16ms/step - loss: 6570802.6240 - age_loss: 823.1293 - income_loss: 6570576.9880 - gender_loss: 1.9846
Epoch 3/10
1000/1000 [==============================] - 20s 20ms/step - loss: 6570792.3360 - age_loss: 791.1411 - income_loss: 6570576.9760 - gender_loss: 1.7661
Epoch 4/10
1000/1000 [==============================] - 17s 17ms/step - loss: 6570810.2200 - age_loss: 848.3705 - income_loss: 6570576.8960 - gender_loss: 2.1191
Epoch 5/10
1000/1000 [==============================] - 17s 17ms/step - loss: 6570800.5120 - age_loss: 806.3608 - income_loss: 6570576.9840 - gender_loss: 2.1932
Epoch 6/10
1000/1000 [==============================] - 15s 15ms/step - loss: 6570811.3880 - age_loss: 833.1162 - income_loss: 6570576.9240 - gender_loss: 2.6179
Epoch 7/10
1000/1000 [=====

### Inception modules

In [71]:
from keras import layers


x = Input(shape=(128,128,3), dtype='float32')
branch_a = layers.Conv2D(128, 1,
                         activation='relu', strides=2)(x)                  
branch_b = layers.Conv2D(128, 1, activation='relu')(x)                     
branch_b = layers.Conv2D(128, 3, activation='relu', strides=2, padding='same')(branch_b)   

branch_c = layers.AveragePooling2D(3, strides=2, padding='same')(x)                        
branch_c = layers.Conv2D(128, 3, activation='relu', padding='same')(branch_c)              

branch_d = layers.Conv2D(128, 1, activation='relu')(x)
branch_d = layers.Conv2D(128, 3, activation='relu', padding='same')(branch_d)
branch_d = layers.Conv2D(128, 3, activation='relu', strides=2, padding='same')(branch_d)
output = layers.concatenate(
    [branch_a, branch_b, branch_c, branch_d], axis=-1)                     

### Residual Connection

In [72]:
# from keras import layers

# x = ...
# y = layers.Conv2D(128, 3, activation='relu', padding='same')(x)    
# y = layers.Conv2D(128, 3, activation='relu', padding='same')(y)
# y = layers.Conv2D(128, 3, activation='relu', padding='same')(y)

# y = layers.add([y, x])

In [73]:
# from keras import layers

# x = ...
# y = layers.Conv2D(128, 3, activation='relu', padding='same')(x)
# y = layers.Conv2D(128, 3, activation='relu', padding='same')(y)
# y = layers.MaxPooling2D(2, strides=2)(y)

# residual = layers.Conv2D(128, 1, strides=2, padding='same')(x)       1

# y = layers.add([y, residual]) 

###  Siamese LSTM model or a shared LSTM

In [76]:
from keras import layers
from keras import Input
from keras.models import Model

lstm = layers.LSTM(32)                                                
left_input = Input(shape=(None, 128))                                 
left_output = lstm(left_input)                                        

right_input = Input(shape=(None, 128))                                
right_output = lstm(right_input)                                      

merged = layers.concatenate([left_output, right_output], axis=-1)     
predictions = layers.Dense(1, activation='sigmoid')(merged)           

model = Model([left_input, right_input], predictions)                 
# model.fit([left_data, right_data], targets)          

###  Siamese vision model

In [ ]:
from keras import layers
from keras import applications
from keras import Input

xception_base = applications.Xception(weights=None,
                                      include_top=False)      1

left_input = Input(shape=(250, 250, 3))                       2
right_input = Input(shape=(250, 250, 3))                      2

left_features = xception_base(left_input)                     3
right_input = xception_base(right_input)                      3

merged_features = layers.concatenate(
    [left_features, right_input], axis=-1)                    4